@startuml
|Content creator|
start
:Submit New/Edited Post;
<<object>>:Post;
<<sendSignal>>:Send Post to the moderation;
<<acceptEvent>> :Wait for check result;
if (Moderation result?) then (Rejected)
  <<sendSignal>>:Send Rejection Notification;
  stop
  |Content creator|
else (Approved)
|Server|
:Publish Post;
endif

:Analyze Post;
:Determine target audience;
<<sendSignal>> :Add to content feed;
-[hidden]->
|Server|

|Viewer|
<<acceptEvent>> :Generate Post Queue;
:View Post;

if (Leave feedback?) then (Yes)
  :Leave feedback;
else (No)
endif
:Generate User Interaction Info;
<<object>>:User Interaction Info;
|Viewer|

|Server|
:Collect interaction info;
:Generate Statistic;
<<object>>:Post Statistic;
<<sendSignal>>:Send Statistic;
-[hidden]->
|Server|

|Content creator|
<<acceptEvent>> :Receive Statistic;
:Analyze Statistic;
|Content creator|

stop
@enduml